Add PSR7 http-server-middleware
reliv/swagger-expressive pull request #4
Opened 2018-10-11 19:04 UTC by jerv13

2018-10-15 16:33 UTC, bradharms commented on composer.json
> +    "psr/http-server-middleware": "^1.0",
I'm guessing this changed from non-semver to semver?

2018-10-15 16:46 UTC, rodmcnew commented
Do we really need all these flags just to turn pretty print on and off? Why not just always either have it on or off?

2018-10-15 17:40 UTC, bradharms approved these changes

2018-10-15 17:47 UTC, rodmcnew commented
My main concern us just the complexity of having a debug flag passed everywhere. It took me a while to dig up what it did and to ensure it doesn't open some security hole. I'd rather not have it at all. Brad and I chatted some and think we should just never pretty print. Let people use the pretty print feature of their browser or other tools if they need it. Not the server's job.

2018-10-15 17:53 UTC, bradharms requested changes
See rod's previous comment.

2018-10-16 17:08 UTC, jerv13 commented
The 'debug' config is common to expressive and the debug construction arg was already in this code base. I did not add it in this PR.  So is really out of scope for the PR.

2018-10-16 20:32 UTC, rodmcnew commented
I'm going to go ahead and merge this regardless of the debug concerns since James explained that code existed previously and was just carried forward to the new expressive version.

2018-10-16 20:32 UTC, merged